In [1]:
import fastbook
fastbook.setup_book()

In [3]:
from fastbook import *
from pandas.api.types import is_string_dtype, is_numeric_dtype, is_categorical_dtype
from fastai.tabular.all import *
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from dtreeviz.trees import *
from IPython.display import Image, display_svg, SVG

pd.options.display.max_rows = 20
pd.options.display.max_columns = 8

In [199]:
import os
import pandas as pd
import numpy as np

cwd = os.getcwd()
print("Current working directory: {0}".format(cwd))

realestate = pd.read_csv("./Ames Real Estate Data.csv", low_memory = False)
HousePrice = pd.read_csv("./Ames_HousePrice.csv")

Current working directory: /home/koz/koz/NYCDSA/AmesWorking


In [200]:
HousePrice.columns

Index(['Unnamed: 0', 'PID', 'GrLivArea', 'SalePrice', 'MSSubClass', 'MSZoning',
       'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF',
       '2ndFlrSF', 'LowQualFinSF', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
    

In [201]:
HousePrice['YrSold'].unique()

array([2010, 2009, 2007, 2008, 2006])

In [202]:
HousePrice['YrSold'].dtype

dtype('int64')

In [204]:
HousePrice['Street'].unique()

array(['Pave', 'Grvl'], dtype=object)

In [205]:
MSZoning_order = ('RL', 'C (all)', 'RM', 'FV', 'RH', 'I (all)', 'A (agr)')
HousePrice['MSZoning'] = HousePrice['MSZoning'].astype('category')
HousePrice['MSZoning'].cat.set_categories(MSZoning_order, ordered=True, inplace=True)

In [206]:
HousePrice['Street'].dtype

dtype('O')

In [207]:
Street_order = ('Pave', 'Grvl')
HousePrice['Street'] = HousePrice['Street'].astype('category')
HousePrice['Street'].cat.set_categories(Street_order, ordered=True, inplace=True)

In [208]:
#HousePrice['Alley'].unique()
#HousePrice['Alley'].fillna(value="No alley access")
HousePrice['Alley'].unique()

array([nan, 'Pave', 'Grvl'], dtype=object)

In [209]:
Alley_order = ('Pave', 'Grvl')
HousePrice['Alley'] = HousePrice['Alley'].astype('category')
HousePrice['Alley'].cat.set_categories(Alley_order, ordered=True, inplace=True)

In [210]:
HousePrice['LotShape'].unique()

array(['Reg', 'IR1', 'IR3', 'IR2'], dtype=object)

In [211]:
LotShape_order = ('Reg', 'IR1', 'IR3', 'IR2')
HousePrice['LotShape'] = HousePrice['LotShape'].astype('category')
HousePrice['LotShape'].cat.set_categories(LotShape_order, ordered=True, inplace=True)

In [212]:
HousePrice['LandContour'].unique()

array(['Lvl', 'Bnk', 'HLS', 'Low'], dtype=object)

In [213]:
LandContour_order = ('Lvl', 'Bnk', 'HLS', 'Low')
HousePrice['LandContour'] = HousePrice['LandContour'].astype('category')
HousePrice['LandContour'].cat.set_categories(LandContour_order, ordered=True, inplace=True)

In [214]:
HousePrice['Utilities'].unique()

array(['AllPub', 'NoSewr'], dtype=object)

In [215]:
Utilities_order = ('AllPub', 'NoSewr')
HousePrice['Utilities'] = HousePrice['Utilities'].astype('category')
HousePrice['Utilities'].cat.set_categories(Utilities_order, ordered=True, inplace=True)

In [216]:
HousePrice['LotConfig'].unique()

array(['Corner', 'Inside', 'FR2', 'CulDSac', 'FR3'], dtype=object)

In [217]:
LotConfig_order = ('Corner', 'Inside', 'FR2', 'CulDSac', 'FR3')
HousePrice['LotConfig'] = HousePrice['LotConfig'].astype('category')
HousePrice['LotConfig'].cat.set_categories(LotConfig_order, ordered=True, inplace=True)

In [218]:
HousePrice['LandSlope'].unique()

array(['Gtl', 'Mod', 'Sev'], dtype=object)

In [219]:
LandSlope_order = ('Gtl', 'Mod', 'Sev')
HousePrice['LandSlope'] = HousePrice['LandSlope'].astype('category')
HousePrice['LandSlope'].cat.set_categories(LandSlope_order, ordered=True, inplace=True)

In [220]:
HousePrice['Neighborhood'].unique()

array(['SWISU', 'Edwards', 'IDOTRR', 'OldTown', 'NWAmes', 'Blmngtn', 'Mitchel', 'NridgHt', 'NAmes', 'CollgCr', 'SawyerW', 'MeadowV', 'BrDale', 'Gilbert', 'Timber', 'Somerst', 'BrkSide', 'NoRidge',
       'Sawyer', 'Crawfor', 'Greens', 'ClearCr', 'GrnHill', 'StoneBr', 'Veenker', 'NPkVill', 'Blueste', 'Landmrk'], dtype=object)

In [221]:
Neighborhood_order = ('SWISU', 'Edwards', 'IDOTRR', 'OldTown', 'NWAmes', 'Blmngtn', 'Mitchel', 'NridgHt', 'NAmes', 'CollgCr', 'SawyerW', 'MeadowV', 'BrDale', 'Gilbert', 'Timber', 'Somerst', 'BrkSide', 'NoRidge',
       'Sawyer', 'Crawfor', 'Greens', 'ClearCr', 'GrnHill', 'StoneBr', 'Veenker', 'NPkVill', 'Blueste', 'Landmrk')
HousePrice['Neighborhood'] = HousePrice['Neighborhood'].astype('category')
HousePrice['Neighborhood'].cat.set_categories(Neighborhood_order, ordered=True, inplace=True)

In [222]:
HousePrice['Condition1'].unique()

array(['Norm', 'RRAn', 'PosN', 'Artery', 'RRAe', 'Feedr', 'PosA', 'RRNn', 'RRNe'], dtype=object)

In [223]:
Condition1_order = ('Norm', 'RRAn', 'PosN', 'Artery', 'RRAe', 'Feedr', 'PosA', 'RRNn', 'RRNe')
HousePrice['Condition1'] = HousePrice['Condition1'].astype('category')
HousePrice['Condition1'].cat.set_categories(Condition1_order, ordered=True, inplace=True)

In [224]:
HousePrice['Condition2'].unique()

array(['Norm', 'PosN', 'Feedr', 'Artery', 'PosA', 'RRNn', 'RRAn', 'RRAe'], dtype=object)

In [225]:
Condition2_order = ('Norm', 'PosN', 'Feedr', 'Artery', 'PosA', 'RRNn', 'RRAn', 'RRAe')
HousePrice['Condition2'] = HousePrice['Condition2'].astype('category')
HousePrice['Condition2'].cat.set_categories(Condition2_order, ordered=True, inplace=True)

In [226]:
HousePrice['BldgType'].unique()

array(['1Fam', 'TwnhsE', '2fmCon', 'Twnhs', 'Duplex'], dtype=object)

In [227]:
BldgType_order = ('1Fam', 'TwnhsE', '2fmCon', 'Twnhs', 'Duplex')
HousePrice['BldgType'] = HousePrice['BldgType'].astype('category')
HousePrice['BldgType'].cat.set_categories(BldgType_order, ordered=True, inplace=True)

In [228]:
HousePrice['HouseStyle'].unique()

array(['1Story', '2Story', 'SFoyer', 'SLvl', '1.5Fin', '2.5Unf', '1.5Unf', '2.5Fin'], dtype=object)

In [229]:
HouseStyle_order = ('1Story', '2Story', 'SFoyer', 'SLvl', '1.5Fin', '2.5Unf', '1.5Unf', '2.5Fin')
HousePrice['HouseStyle'] = HousePrice['HouseStyle'].astype('category')
HousePrice['HouseStyle'].cat.set_categories(HouseStyle_order, ordered=True, inplace=True)

In [230]:
HousePrice['OverallQual'].dtype

dtype('int64')

In [231]:
HousePrice['OverallCond'].dtype

dtype('int64')

In [232]:
HousePrice['YearBuilt'].dtype

dtype('int64')

In [233]:
HousePrice['YearRemodAdd'].dtype

dtype('int64')

In [234]:
HousePrice['RoofStyle'].unique()

array(['Gable', 'Hip', 'Mansard', 'Gambrel', 'Flat', 'Shed'], dtype=object)

In [235]:
RoofStyle_order = ('Gable', 'Hip', 'Mansard', 'Gambrel', 'Flat', 'Shed')
HousePrice['RoofStyle'] = HousePrice['RoofStyle'].astype('category')
HousePrice['RoofStyle'].cat.set_categories(RoofStyle_order, ordered=True, inplace=True)

In [236]:
HousePrice['RoofMatl'].unique()

array(['CompShg', 'Tar&Grv', 'WdShake', 'WdShngl', 'Metal', 'Roll', 'Membran'], dtype=object)

In [238]:
RoofMatl_order = ('CompShg', 'Tar&Grv', 'WdShake', 'WdShngl', 'Metal', 'Roll', 'Membran')
HousePrice['RoofMatl'] = HousePrice['RoofMatl'].astype('category')
HousePrice['RoofMatl'].cat.set_categories(RoofMatl_order, ordered=True, inplace=True)

In [239]:
HousePrice['Exterior1st'].unique()

array(['Wd Sdng', 'HdBoard', 'MetalSd', 'VinylSd', 'WdShing', 'Plywood', 'Stucco', 'CemntBd', 'BrkFace', 'AsbShng', 'BrkComm', 'ImStucc', 'AsphShn', 'CBlock', 'PreCast'], dtype=object)

In [240]:
Exterior1st_order = 'Wd Sdng', 'HdBoard', 'MetalSd', 'VinylSd', 'WdShing', 'Plywood', 'Stucco', 'CemntBd', 'BrkFace', 'AsbShng', 'BrkComm', 'ImStucc', 'AsphShn', 'CBlock', 'PreCast'
HousePrice['Exterior1st'] = HousePrice['Exterior1st'].astype('category')
HousePrice['Exterior1st'].cat.set_categories(Exterior1st_order, ordered=True, inplace=True)

In [241]:
HousePrice['Exterior2nd'].unique()

array(['Wd Sdng', 'HdBoard', 'MetalSd', 'VinylSd', 'Wd Shng', 'Plywood', 'Stucco', 'CmentBd', 'AsbShng', 'ImStucc', 'BrkFace', 'Brk Cmn', 'CBlock', 'AsphShn', 'Stone', 'PreCast'], dtype=object)

In [242]:
Exterior2nd_order = 'Wd Sdng', 'HdBoard', 'MetalSd', 'VinylSd', 'Wd Shng', 'Plywood', 'Stucco', 'CmentBd', 'AsbShng', 'ImStucc', 'BrkFace', 'Brk Cmn', 'CBlock', 'AsphShn', 'Stone', 'PreCast'
HousePrice['Exterior2nd'] = HousePrice['Exterior2nd'].astype('category')
HousePrice['Exterior2nd'].cat.set_categories(Exterior2nd_order, ordered=True, inplace=True)

In [243]:
HousePrice['MasVnrType'].unique()

array(['None', 'BrkFace', 'Stone', 'BrkCmn', nan], dtype=object)

In [245]:
MasVnrType_order = 'None', 'BrkFace', 'Stone', 'BrkCmn'
HousePrice['MasVnrType'] = HousePrice['MasVnrType'].astype('category')
HousePrice['MasVnrType'].cat.set_categories(MasVnrType_order, ordered=True, inplace=True)

In [246]:
HousePrice['MasVnrArea'].dtype

dtype('float64')

In [247]:
HousePrice['ExterQual'].unique()

array(['TA', 'Gd', 'Fa', 'Ex'], dtype=object)

In [248]:
ExterQual_order = 'TA', 'Fa', 'Gd', 'Ex'
HousePrice['ExterQual'] = HousePrice['ExterQual'].astype('category')
HousePrice['ExterQual'].cat.set_categories(ExterQual_order, ordered=True, inplace=True)

In [249]:
HousePrice['ExterCond'].unique()

array(['TA', 'Gd', 'Fa', 'Ex', 'Po'], dtype=object)

In [250]:
ExterCond_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex' 
HousePrice['ExterCond'] = HousePrice['ExterCond'].astype('category')
HousePrice['ExterCond'].cat.set_categories(ExterCond_order, ordered=True, inplace=True)

In [251]:
HousePrice['Foundation'].unique()

array(['CBlock', 'BrkTil', 'PConc', 'Slab', 'Stone', 'Wood'], dtype=object)

In [252]:
Foundation_order = 'CBlock', 'BrkTil', 'PConc', 'Slab', 'Stone', 'Wood'
HousePrice['Foundation'] = HousePrice['Foundation'].astype('category')
HousePrice['Foundation'].cat.set_categories(Foundation_order, ordered=True, inplace=True)

In [253]:
HousePrice['BsmtQual'].unique()

array(['TA', 'Gd', 'Fa', nan, 'Ex', 'Po'], dtype=object)

In [255]:
BsmtQual_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['BsmtQual'] = HousePrice['BsmtQual'].astype('category')
HousePrice['BsmtQual'].cat.set_categories(BsmtQual_order, ordered=True, inplace=True)

In [256]:
HousePrice['BsmtCond'].unique()

array(['TA', nan, 'Fa', 'Gd', 'Ex', 'Po'], dtype=object)

In [257]:
BsmtCond_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['BsmtCond'] = HousePrice['BsmtCond'].astype('category')
HousePrice['BsmtCond'].cat.set_categories(BsmtCond_order, ordered=True, inplace=True)

In [258]:
HousePrice['BsmtExposure'].unique()

array(['No', 'Mn', nan, 'Gd', 'Av'], dtype=object)

In [259]:
BsmtExposure_order = 'No', 'Mn', 'Gd', 'Av'
HousePrice['BsmtExposure'] = HousePrice['BsmtExposure'].astype('category')
HousePrice['BsmtExposure'].cat.set_categories(BsmtExposure_order, ordered=True, inplace=True)

In [260]:
HousePrice['BsmtFinType1'].unique()

array(['Rec', 'GLQ', 'ALQ', 'Unf', nan, 'BLQ', 'LwQ'], dtype=object)

In [261]:
BsmtFinType1_order = 'Rec', 'GLQ', 'ALQ', 'Unf', 'BLQ', 'LwQ'
HousePrice['BsmtFinType1'] = HousePrice['BsmtFinType1'].astype('category')
HousePrice['BsmtFinType1'].cat.set_categories(BsmtFinType1_order, ordered=True, inplace=True)

In [262]:
HousePrice['BsmtFinSF1'].dtype

dtype('float64')

In [263]:
HousePrice['BsmtFinSF2'].dtype

dtype('float64')

In [264]:
HousePrice['BsmtFinType2'].unique()

array(['Unf', 'ALQ', nan, 'GLQ', 'BLQ', 'LwQ', 'Rec'], dtype=object)

In [265]:
BsmtFinType2_order = 'Rec', 'GLQ', 'ALQ', 'Unf', 'BLQ', 'LwQ'
HousePrice['BsmtFinType2'] = HousePrice['BsmtFinType2'].astype('category')
HousePrice['BsmtFinType2'].cat.set_categories(BsmtFinType2_order, ordered=True, inplace=True)

In [266]:
HousePrice['BsmtUnfSF'].dtype

dtype('float64')

In [267]:
HousePrice['TotalBsmtSF'].dtype

dtype('float64')

In [268]:
HousePrice['Heating'].unique()

array(['GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor'], dtype=object)

In [269]:
Heating_order = 'GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor'
HousePrice['Heating'] = HousePrice['Heating'].astype('category')
HousePrice['Heating'].cat.set_categories(Heating_order, ordered=True, inplace=True)

In [270]:
HousePrice['HeatingQC'].unique()

array(['TA', 'Ex', 'Gd', 'Fa', 'Po'], dtype=object)

In [271]:
HeatingQC_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['HeatingQC'] = HousePrice['HeatingQC'].astype('category')
HousePrice['HeatingQC'].cat.set_categories(HeatingQC_order, ordered=True, inplace=True)

In [272]:
HousePrice['CentralAir'].unique()

array(['Y', 'N'], dtype=object)

In [273]:
CentralAir_order = 'Y', 'N'
HousePrice['CentralAir'] = HousePrice['CentralAir'].astype('category')
HousePrice['CentralAir'].cat.set_categories(CentralAir_order, ordered=True, inplace=True)

In [274]:
HousePrice['Electrical'].unique()

array(['SBrkr', 'FuseF', 'FuseA', 'FuseP', nan], dtype=object)

In [275]:
Electrical_order = 'SBrkr', 'FuseF', 'FuseA', 'FuseP'
HousePrice['Electrical'] = HousePrice['Electrical'].astype('category')
HousePrice['Electrical'].cat.set_categories(Electrical_order, ordered=True, inplace=True)

In [276]:
HousePrice['1stFlrSF'].dtype

dtype('int64')

In [277]:
HousePrice['2ndFlrSF'].dtype

dtype('int64')

In [278]:
HousePrice['LowQualFinSF'].dtype

dtype('int64')

In [279]:
HousePrice['BsmtFullBath'].dtype

dtype('float64')

In [123]:
HousePrice['BsmtHalfBath'].dtype

dtype('float64')

In [280]:
HousePrice['HalfBath'].dtype

dtype('int64')

In [281]:
HousePrice['BedroomAbvGr'].dtype

dtype('int64')

In [282]:
HousePrice['KitchenAbvGr'].dtype

dtype('int64')

In [283]:
HousePrice['KitchenQual'].unique()

array(['TA', 'Gd', 'Ex', 'Fa', 'Po'], dtype=object)

In [284]:
KitchenQual_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['KitchenQual'] = HousePrice['KitchenQual'].astype('category')
HousePrice['KitchenQual'].cat.set_categories(KitchenQual_order, ordered=True, inplace=True)

In [285]:
HousePrice['TotRmsAbvGrd'].dtype

dtype('int64')

In [286]:
HousePrice['Functional'].unique()

array(['Typ', 'Min2', 'Min1', 'Mod', 'Sal', 'Maj1', 'Maj2'], dtype=object)

In [287]:
Functional_order = 'Typ', 'Min2', 'Min1', 'Mod', 'Sal', 'Maj1', 'Maj2'
HousePrice['Functional'] = HousePrice['Functional'].astype('category')
HousePrice['Functional'].cat.set_categories(Functional_order, ordered=True, inplace=True)

In [288]:
HousePrice['Fireplaces'].dtype

dtype('int64')

In [289]:
HousePrice['FireplaceQu'].unique()

array(['Gd', nan, 'Ex', 'TA', 'Fa', 'Po'], dtype=object)

In [290]:
FireplaceQu_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['FireplaceQu'] = HousePrice['FireplaceQu'].astype('category')
HousePrice['FireplaceQu'].cat.set_categories(FireplaceQu_order, ordered=True, inplace=True)

In [291]:
HousePrice['GarageType'].unique()

array(['Detchd', 'Attchd', 'BuiltIn', 'Basment', nan, '2Types', 'CarPort'], dtype=object)

In [292]:
GarageType_order = 'Detchd', 'Attchd', 'BuiltIn', 'Basment', '2Types', 'CarPort'
HousePrice['GarageType'] = HousePrice['GarageType'].astype('category')
HousePrice['GarageType'].cat.set_categories(GarageType_order, ordered=True, inplace=True)

In [293]:
HousePrice['GarageType'].unique()

['Detchd', 'Attchd', 'BuiltIn', 'Basment', NaN, '2Types', 'CarPort']
Categories (6, object): ['Detchd' < 'Attchd' < 'BuiltIn' < 'Basment' < '2Types' < 'CarPort']

In [294]:
HousePrice['GarageYrBlt'].dtype

dtype('float64')

In [295]:
HousePrice['GarageFinish'].unique()

array(['Unf', 'Fin', 'RFn', nan], dtype=object)

In [296]:
GarageFinish_order = 'Unf', 'Fin', 'RFn'
HousePrice['GarageFinish'] = HousePrice['GarageFinish'].astype('category')
HousePrice['GarageFinish'].cat.set_categories(GarageFinish_order, ordered=True, inplace=True)

In [297]:
HousePrice['GarageCars'].dtype

dtype('float64')

In [298]:
HousePrice['GarageArea'].dtype

dtype('float64')

In [299]:
HousePrice['GarageQual'].unique()

array(['TA', nan, 'Fa', 'Gd', 'Po', 'Ex'], dtype=object)

In [300]:
GarageQual_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['GarageQual'] = HousePrice['GarageQual'].astype('category')
HousePrice['GarageQual'].cat.set_categories(GarageQual_order, ordered=True, inplace=True)

In [301]:
HousePrice['GarageCond'].unique()

array(['TA', 'Po', nan, 'Fa', 'Gd', 'Ex'], dtype=object)

In [302]:
GarageCond_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['GarageCond'] = HousePrice['GarageCond'].astype('category')
HousePrice['GarageCond'].cat.set_categories(GarageCond_order, ordered=True, inplace=True)

In [303]:
HousePrice['PavedDrive'].unique()

array(['Y', 'N', 'P'], dtype=object)

In [304]:
PavedDrive_order = 'Y', 'N', 'P'
HousePrice['PavedDrive'] = HousePrice['PavedDrive'].astype('category')
HousePrice['PavedDrive'].cat.set_categories(PavedDrive_order, ordered=True, inplace=True)

In [305]:
HousePrice['WoodDeckSF'].dtype

dtype('int64')

In [306]:
HousePrice['OpenPorchSF'].dtype

dtype('int64')

In [307]:
HousePrice['EnclosedPorch'].dtype

dtype('int64')

In [308]:
HousePrice['3SsnPorch'].dtype

dtype('int64')

In [311]:
HousePrice['ScreenPorch'].dtype

dtype('int64')

In [312]:
HousePrice['PoolArea'].dtype

dtype('int64')

In [313]:
HousePrice['PoolQC'].unique()

array([nan, 'Ex', 'Gd', 'Fa', 'TA'], dtype=object)

In [314]:
PoolQC_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['PoolQC'] = HousePrice['PoolQC'].astype('category')
HousePrice['PoolQC'].cat.set_categories(PoolQC_order, ordered=True, inplace=True)

In [315]:
HousePrice['Fence'].unique()

array([nan, 'GdWo', 'MnPrv', 'GdPrv', 'MnWw'], dtype=object)

In [316]:
Fence_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['Fence'] = HousePrice['Fence'].astype('category')
HousePrice['Fence'].cat.set_categories(Fence_order, ordered=True, inplace=True)

In [317]:
HousePrice['MiscFeature'].unique()

array([nan, 'Shed', 'Othr', 'Gar2', 'TenC'], dtype=object)

In [318]:
MiscFeature_order = 'Shed', 'Othr', 'Gar2', 'TenC'
HousePrice['MiscFeature'] = HousePrice['MiscFeature'].astype('category')
HousePrice['MiscFeature'].cat.set_categories(MiscFeature_order, ordered=True, inplace=True)

In [320]:
HousePrice['MiscVal'].dtype

dtype('int64')

In [321]:
HousePrice['MoSold'].dtype

dtype('int64')

In [322]:
HousePrice['YrSold'].dtype

dtype('int64')

In [323]:
HousePrice['SaleType'].unique()

array(['WD ', 'ConLD', 'New', 'Oth', 'ConLw', 'COD', 'CWD', 'Con', 'ConLI', 'VWD'], dtype=object)

In [324]:
SaleType_order = 'WD ', 'ConLD', 'New', 'Oth', 'ConLw', 'COD', 'CWD', 'Con', 'ConLI', 'VWD'
HousePrice['SaleType'] = HousePrice['SaleType'].astype('category')
HousePrice['SaleType'].cat.set_categories(SaleType_order, ordered=True, inplace=True)

In [325]:
HousePrice['SaleCondition'].unique()

array(['Normal', 'Partial', 'AdjLand', 'Abnorml', 'Alloca', 'Family'], dtype=object)

In [326]:
SaleCondition_order = 'Normal', 'Partial', 'AdjLand', 'Abnorml', 'Alloca', 'Family'
HousePrice['SaleCondition'] = HousePrice['SaleCondition'].astype('category')
HousePrice['SaleCondition'].cat.set_categories(SaleCondition_order, ordered=True, inplace=True)

In [183]:
SaleType_order = 'WD ', 'ConLD', 'New', 'Oth', 'ConLw', 'COD', 'CWD', 'Con', 'ConLI', 'VWD'
HousePrice['SaleType'] = HousePrice['SaleType'].astype('category')
HousePrice['SaleType'].cat.set_categories(SaleType_order, ordered=True, inplace=True)

In [354]:
HousePrice_small = HousePrice[['GrLivArea', 'LotArea', 'YearBuilt', 'GarageCars', 'YrSold', 'SalePrice']]
HousePrice_small.shape

(2580, 6)

In [355]:
test_cond = HousePrice_small['YrSold'] == 2010
remainder_cond = HousePrice_small['YrSold'] < 2010
HousePrice_test = HousePrice[test_cond]
HousePrice_test.shape
HousePrice_train_and_valid = HousePrice_small[remainder_cond]
HousePrice_train_and_valid.shape

(2265, 6)

In [356]:
valid_cond = HousePrice_train_and_valid['YrSold'] == 2009
train_idx = np.where(~valid_cond)[0]
valid_idx = np.where(valid_cond)[0]

splits = (list(train_idx), list(valid_idx))

In [357]:
dep_var = 'SalePrice'
procs = [ Categorify, FillMissing ]

In [358]:
cont, cat = cont_cat_split(HousePrice_train_and_valid, 1, dep_var=dep_var)
print(cont, cat)
# import pdb; pdb.set_trace()
tpo = TabularPandas(HousePrice_train_and_valid, procs, cont, cat, y_names=dep_var, splits=splits)
len(tpo.train), len(tpo.valid)

['GrLivArea', 'LotArea', 'YearBuilt', 'GarageCars', 'YrSold'] []


(1680, 585)

In [359]:
def root_mse(pred, y): return round(math.sqrt(((pred-y)**2).mean()), 6)
def model_rmse(m, xs, y): return root_mse( m.predict(xs), y)

In [360]:
xs, y = tpo.train.xs, tpo.train.y
valid_xs, valid_y = tpo.valid.xs, tpo.valid.y

In [362]:
m = DecisionTreeRegressor()
m.fit(xs, y)

DecisionTreeRegressor()

In [363]:
model_rmse(m, xs, y)

413.156944

In [364]:
model_rmse(m, valid_xs, valid_y)

82512.465504

In [367]:
def rf(xs, y, n_estimators=40, max_samples=200,
       max_features=0.5, min_samples_leaf=5, **kwargs):
    return RandomForestRegressor(n_jobs=-1, n_estimators=n_estimators,
        max_samples=max_samples, max_features=max_features,
        min_samples_leaf=min_samples_leaf, oob_score=True).fit(xs, y)

In [368]:
m = rf(xs, y);

In [369]:
model_rmse(m, xs, y)

38017.159945

In [ ]:
model_rmse(m, xs, y)

model_rmse(m, xs, y)