In [1]:
import fastbook
fastbook.setup_book()

In [3]:
from fastbook import *
from pandas.api.types import is_string_dtype, is_numeric_dtype, is_categorical_dtype
from fastai.tabular.all import *
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from dtreeviz.trees import *
from IPython.display import Image, display_svg, SVG

pd.options.display.max_rows = 20
pd.options.display.max_columns = 8

In [5]:
import os
import pandas as pd
import numpy as np

cwd = os.getcwd()
print("Current working directory: {0}".format(cwd))

realestate = pd.read_csv("./Ames Real Estate Data.csv", low_memory = False)
HousePrice = pd.read_csv("./Ames_HousePrice.csv")

Current working directory: /home/koz/koz/NYCDSA/AmesWorking


In [6]:
HousePrice.columns

Index(['Unnamed: 0', 'PID', 'GrLivArea', 'SalePrice', 'MSSubClass', 'MSZoning',
       'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF',
       '2ndFlrSF', 'LowQualFinSF', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
    

In [11]:
HousePrice['YrSold'].unique()

array([2010, 2009, 2007, 2008, 2006])

In [26]:
HousePrice['Street'].unique()

array(['Pave', 'Grvl'], dtype=object)

In [20]:
MSZoning_order = ('RL', 'C (all)', 'RM', 'FV', 'RH', 'I (all)', 'A (agr)')
HousePrice['MSZoning'] = HousePrice['MSZoning'].astype('category')
HousePrice['MSZoning'].cat.set_categories(MSZoning_order, ordered=True, inplace=True)

In [27]:
HousePrice['Street'].dtype

dtype('O')

In [28]:
Street_order = ('Pave', 'Grvl')
HousePrice['Street'] = HousePrice['Street'].astype('category')
HousePrice['Street'].cat.set_categories(Street_order, ordered=True, inplace=True)

In [31]:
#HousePrice['Alley'].unique()
#HousePrice['Alley'].fillna(value="No alley access")
HousePrice['Alley'].unique()

array([nan, 'Pave', 'Grvl'], dtype=object)

In [32]:
Alley_order = ('Pave', 'Grvl')
HousePrice['Alley'] = HousePrice['Alley'].astype('category')
HousePrice['Alley'].cat.set_categories(Alley_order, ordered=True, inplace=True)

In [33]:
HousePrice['LotShape'].unique()

array(['Reg', 'IR1', 'IR3', 'IR2'], dtype=object)

In [34]:
LotShape_order = ('Reg', 'IR1', 'IR3', 'IR2')
HousePrice['LotShape'] = HousePrice['LotShape'].astype('category')
HousePrice['LotShape'].cat.set_categories(LotShape_order, ordered=True, inplace=True)

In [38]:
HousePrice['LandContour'].unique()

['Lvl', 'Bnk', 'HLS', 'Low']
Categories (4, object): ['Lvl' < 'Bnk' < 'HLS' < 'Low']

In [36]:
LandContour_order = ('Lvl', 'Bnk', 'HLS', 'Low')
HousePrice['LandContour'] = HousePrice['LandContour'].astype('category')
HousePrice['LandContour'].cat.set_categories(LandContour_order, ordered=True, inplace=True)

In [39]:
HousePrice['Utilities'].unique()

array(['AllPub', 'NoSewr'], dtype=object)

In [40]:
Utilities_order = ('AllPub', 'NoSewr')
HousePrice['Utilities'] = HousePrice['Utilities'].astype('category')
HousePrice['Utilities'].cat.set_categories(Utilities_order, ordered=True, inplace=True)

In [42]:
HousePrice['LotConfig'].unique()

array(['Corner', 'Inside', 'FR2', 'CulDSac', 'FR3'], dtype=object)

In [43]:
LotConfig_order = ('Corner', 'Inside', 'FR2', 'CulDSac', 'FR3')
HousePrice['LotConfig'] = HousePrice['LotConfig'].astype('category')
HousePrice['LotConfig'].cat.set_categories(LotConfig_order, ordered=True, inplace=True)

In [45]:
HousePrice['LandSlope'].unique()

array(['Gtl', 'Mod', 'Sev'], dtype=object)

In [46]:
LandSlope_order = ('Gtl', 'Mod', 'Sev')
HousePrice['LandSlope'] = HousePrice['LandSlope'].astype('category')
HousePrice['LandSlope'].cat.set_categories(LandSlope_order, ordered=True, inplace=True)

In [48]:
HousePrice['Neighborhood'].unique()

array(['SWISU', 'Edwards', 'IDOTRR', 'OldTown', 'NWAmes', 'Blmngtn', 'Mitchel', 'NridgHt', 'NAmes', 'CollgCr', 'SawyerW', 'MeadowV', 'BrDale', 'Gilbert', 'Timber', 'Somerst', 'BrkSide', 'NoRidge',
       'Sawyer', 'Crawfor', 'Greens', 'ClearCr', 'GrnHill', 'StoneBr', 'Veenker', 'NPkVill', 'Blueste', 'Landmrk'], dtype=object)

In [49]:
Neighborhood_order = ('SWISU', 'Edwards', 'IDOTRR', 'OldTown', 'NWAmes', 'Blmngtn', 'Mitchel', 'NridgHt', 'NAmes', 'CollgCr', 'SawyerW', 'MeadowV', 'BrDale', 'Gilbert', 'Timber', 'Somerst', 'BrkSide', 'NoRidge',
       'Sawyer', 'Crawfor', 'Greens', 'ClearCr', 'GrnHill', 'StoneBr', 'Veenker', 'NPkVill', 'Blueste', 'Landmrk')
HousePrice['Neighborhood'] = HousePrice['Neighborhood'].astype('category')
HousePrice['Neighborhood'].cat.set_categories(Neighborhood_order, ordered=True, inplace=True)

In [51]:
HousePrice['Condition1'].unique()

array(['Norm', 'RRAn', 'PosN', 'Artery', 'RRAe', 'Feedr', 'PosA', 'RRNn', 'RRNe'], dtype=object)

In [52]:
Condition1_order = ('Norm', 'RRAn', 'PosN', 'Artery', 'RRAe', 'Feedr', 'PosA', 'RRNn', 'RRNe')
HousePrice['Condition1'] = HousePrice['Condition1'].astype('category')
HousePrice['Condition1'].cat.set_categories(Condition1_order, ordered=True, inplace=True)

In [54]:
HousePrice['Condition2'].unique()

array(['Norm', 'PosN', 'Feedr', 'Artery', 'PosA', 'RRNn', 'RRAn', 'RRAe'], dtype=object)

In [55]:
Condition2_order = ('Norm', 'PosN', 'Feedr', 'Artery', 'PosA', 'RRNn', 'RRAn', 'RRAe')
HousePrice['Condition2'] = HousePrice['Condition2'].astype('category')
HousePrice['Condition2'].cat.set_categories(Condition2_order, ordered=True, inplace=True)

In [57]:
HousePrice['BldgType'].unique()

array(['1Fam', 'TwnhsE', '2fmCon', 'Twnhs', 'Duplex'], dtype=object)

In [58]:
BldgType_order = ('1Fam', 'TwnhsE', '2fmCon', 'Twnhs', 'Duplex')
HousePrice['BldgType'] = HousePrice['BldgType'].astype('category')
HousePrice['BldgType'].cat.set_categories(BldgType_order, ordered=True, inplace=True)

In [60]:
HousePrice['HouseStyle'].unique()

array(['1Story', '2Story', 'SFoyer', 'SLvl', '1.5Fin', '2.5Unf', '1.5Unf', '2.5Fin'], dtype=object)

In [61]:
HouseStyle_order = ('1Story', '2Story', 'SFoyer', 'SLvl', '1.5Fin', '2.5Unf', '1.5Unf', '2.5Fin')
HousePrice['HouseStyle'] = HousePrice['HouseStyle'].astype('category')
HousePrice['HouseStyle'].cat.set_categories(HouseStyle_order, ordered=True, inplace=True)

In [63]:
HousePrice['OverallQual'].dtype

dtype('int64')

In [65]:
HousePrice['OverallCond'].dtype

dtype('int64')

In [68]:
HousePrice['YearBuilt'].dtype

dtype('int64')

In [70]:
HousePrice['YearRemodAdd'].dtype

dtype('int64')

In [71]:
HousePrice['RoofStyle'].unique()

array(['Gable', 'Hip', 'Mansard', 'Gambrel', 'Flat', 'Shed'], dtype=object)

In [72]:
RoofStyle_order = ('Gable', 'Hip', 'Mansard', 'Gambrel', 'Flat', 'Shed')
HousePrice['RoofStyle'] = HousePrice['RoofStyle'].astype('category')
HousePrice['RoofStyle'].cat.set_categories(RoofStyle_order, ordered=True, inplace=True)

In [74]:
HousePrice['RoofMatl'].unique()

array(['CompShg', 'Tar&Grv', 'WdShake', 'WdShngl', 'Metal', 'Roll', 'Membran'], dtype=object)

In [76]:
RoofMatl_order = ('CompShg', 'Tar&Grv', 'WdShake', 'WdShngl', 'Metal', 'Roll', 'Membran')
HousePrice['RoofMatl'] = HousePrice['RoofMatl'].astype('category')
HousePrice['RoofMatl'].cat.set_categories(RoofMatl_order, ordered=True, inplace=True)

In [78]:
HousePrice['Exterior1st'].unique()

array(['Wd Sdng', 'HdBoard', 'MetalSd', 'VinylSd', 'WdShing', 'Plywood', 'Stucco', 'CemntBd', 'BrkFace', 'AsbShng', 'BrkComm', 'ImStucc', 'AsphShn', 'CBlock', 'PreCast'], dtype=object)

In [79]:
Exterior1st_order = 'Wd Sdng', 'HdBoard', 'MetalSd', 'VinylSd', 'WdShing', 'Plywood', 'Stucco', 'CemntBd', 'BrkFace', 'AsbShng', 'BrkComm', 'ImStucc', 'AsphShn', 'CBlock', 'PreCast'
HousePrice['Exterior1st'] = HousePrice['Exterior1st'].astype('category')
HousePrice['Exterior1st'].cat.set_categories(Exterior1st_order, ordered=True, inplace=True)

In [81]:
HousePrice['Exterior2nd'].unique()

array(['Wd Sdng', 'HdBoard', 'MetalSd', 'VinylSd', 'Wd Shng', 'Plywood', 'Stucco', 'CmentBd', 'AsbShng', 'ImStucc', 'BrkFace', 'Brk Cmn', 'CBlock', 'AsphShn', 'Stone', 'PreCast'], dtype=object)

In [82]:
Exterior2nd_order = 'Wd Sdng', 'HdBoard', 'MetalSd', 'VinylSd', 'Wd Shng', 'Plywood', 'Stucco', 'CmentBd', 'AsbShng', 'ImStucc', 'BrkFace', 'Brk Cmn', 'CBlock', 'AsphShn', 'Stone', 'PreCast'
HousePrice['Exterior2nd'] = HousePrice['Exterior2nd'].astype('category')
HousePrice['Exterior2nd'].cat.set_categories(Exterior2nd_order, ordered=True, inplace=True)

In [83]:
HousePrice['MasVnrType'].unique()

array(['None', 'BrkFace', 'Stone', 'BrkCmn', nan], dtype=object)

In [84]:
MasVnrType_order = 'None', 'BrkFace', 'Stone', 'BrkCmn'
HousePrice['MasVnrType'] = HousePrice['MasVnrType'].astype('category')
HousePrice['MasVnrType'].cat.set_categories(MasVnrType_order, ordered=True, inplace=True)

In [86]:
HousePrice['MasVnrArea'].dtype

dtype('float64')

In [87]:
HousePrice['ExterQual'].unique()

array(['TA', 'Gd', 'Fa', 'Ex'], dtype=object)

In [91]:
ExterQual_order = 'TA', 'Fa', 'Gd', 'Ex'
HousePrice['ExterQual'] = HousePrice['ExterQual'].astype('category')
HousePrice['ExterQual'].cat.set_categories(ExterQual_order, ordered=True, inplace=True)

In [89]:
HousePrice['ExterCond'].unique()

array(['TA', 'Gd', 'Fa', 'Ex', 'Po'], dtype=object)

In [93]:
ExterCond_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex' 
HousePrice['ExterCond'] = HousePrice['ExterCond'].astype('category')
HousePrice['ExterCond'].cat.set_categories(ExterCond_order, ordered=True, inplace=True)

In [92]:
HousePrice['Foundation'].unique()

array(['CBlock', 'BrkTil', 'PConc', 'Slab', 'Stone', 'Wood'], dtype=object)

In [94]:
Foundation_order = 'CBlock', 'BrkTil', 'PConc', 'Slab', 'Stone', 'Wood'
HousePrice['Foundation'] = HousePrice['Foundation'].astype('category')
HousePrice['Foundation'].cat.set_categories(Foundation_order, ordered=True, inplace=True)

In [95]:
HousePrice['BsmtQual'].unique()

array(['TA', 'Gd', 'Fa', nan, 'Ex', 'Po'], dtype=object)

In [96]:
BsmtQual_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['BsmtQual'] = HousePrice[c'BsmtQual'].astype('category')
HousePrice['BsmtQual'].cat.set_categories(BsmtQual_order, ordered=True, inplace=True)

In [97]:
HousePrice['BsmtCond'].unique()

array(['TA', nan, 'Fa', 'Gd', 'Ex', 'Po'], dtype=object)

In [98]:
BsmtCond_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['BsmtCond'] = HousePrice['BsmtCond'].astype('category')
HousePrice['BsmtCond'].cat.set_categories(BsmtCond_order, ordered=True, inplace=True)

In [99]:
HousePrice['BsmtExposure'].unique()

array(['No', 'Mn', nan, 'Gd', 'Av'], dtype=object)

In [100]:
BsmtExposure_order = 'No', 'Mn', 'Gd', 'Av'
HousePrice['BsmtExposure'] = HousePrice['BsmtExposure'].astype('category')
HousePrice['BsmtExposure'].cat.set_categories(BsmtExposure_order, ordered=True, inplace=True)

In [101]:
HousePrice['BsmtFinType1'].unique()

array(['Rec', 'GLQ', 'ALQ', 'Unf', nan, 'BLQ', 'LwQ'], dtype=object)

In [103]:
BsmtFinType1_order = 'Rec', 'GLQ', 'ALQ', 'Unf', 'BLQ', 'LwQ'
HousePrice['BsmtFinType1'] = HousePrice['BsmtFinType1'].astype('category')
HousePrice['BsmtFinType1'].cat.set_categories(BsmtFinType1_order, ordered=True, inplace=True)

In [104]:
HousePrice['BsmtFinSF1'].dtype

dtype('float64')

In [105]:
HousePrice['BsmtFinSF2'].dtype

dtype('float64')

In [106]:
HousePrice['BsmtFinType2'].unique()

array(['Unf', 'ALQ', nan, 'GLQ', 'BLQ', 'LwQ', 'Rec'], dtype=object)

In [108]:
BsmtFinType2_order = 'Rec', 'GLQ', 'ALQ', 'Unf', 'BLQ', 'LwQ'
HousePrice['BsmtFinType2'] = HousePrice['BsmtFinType2'].astype('category')
HousePrice['BsmtFinType2'].cat.set_categories(BsmtFinType2_order, ordered=True, inplace=True)

In [109]:
HousePrice['BsmtUnfSF'].dtype

dtype('float64')

In [110]:
HousePrice['TotalBsmtSF'].dtype

dtype('float64')

In [111]:
HousePrice['Heating'].unique()

array(['GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor'], dtype=object)

In [112]:
Heating_order = 'GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor'
HousePrice['Heating'] = HousePrice['Heating'].astype('category')
HousePrice['Heating'].cat.set_categories(Heating_order, ordered=True, inplace=True)

In [113]:
HousePrice['HeatingQC'].unique()

array(['TA', 'Ex', 'Gd', 'Fa', 'Po'], dtype=object)

In [114]:
HeatingQC_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['HeatingQC'] = HousePrice['HeatingQC'].astype('category')
HousePrice['HeatingQC'].cat.set_categories(HeatingQC_order, ordered=True, inplace=True)

In [115]:
HousePrice['CentralAir'].unique()

array(['Y', 'N'], dtype=object)

In [116]:
CentralAir_order = 'Y', 'N'
HousePrice['CentralAir'] = HousePrice['CentralAir'].astype('category')
HousePrice['CentralAir'].cat.set_categories(CentralAir_order, ordered=True, inplace=True)

In [144]:
HousePrice['Electrical'].unique()

['SBrkr', 'FuseF', 'FuseA', 'FuseP', NaN]
Categories (4, object): ['SBrkr' < 'FuseF' < 'FuseA' < 'FuseP']

In [145]:
Electrical_order = 'SBrkr', 'FuseF', 'FuseA', 'FuseP'
HousePrice['Electrical'] = HousePrice['Electrical'].astype('category')
HousePrice['Electrical'].cat.set_categories(Electrical_order, ordered=True, inplace=True)

In [119]:
HousePrice['1stFlrSF'].dtype

dtype('int64')

In [120]:
HousePrice['2ndFlrSF'].dtype

dtype('int64')

In [121]:
HousePrice['LowQualFinSF'].dtype

dtype('int64')

In [122]:
HousePrice['BsmtFullBath'].dtype

dtype('float64')

In [123]:
HousePrice['BsmtHalfBath'].dtype

dtype('float64')

In [125]:
HousePrice['HalfBath'].dtype

dtype('int64')

In [126]:
HousePrice['BedroomAbvGr'].dtype

dtype('int64')

In [127]:
HousePrice['KitchenAbvGr'].dtype

dtype('int64')

In [129]:
HousePrice['KitchenQual'].unique()

array(['TA', 'Gd', 'Ex', 'Fa', 'Po'], dtype=object)

In [130]:
KitchenQual_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['KitchenQual'] = HousePrice['KitchenQual'].astype('category')
HousePrice['KitchenQual'].cat.set_categories(KitchenQual_order, ordered=True, inplace=True)

In [131]:
HousePrice['TotRmsAbvGrd'].dtype

dtype('int64')

In [133]:
HousePrice['Functional'].unique()

array(['Typ', 'Min2', 'Min1', 'Mod', 'Sal', 'Maj1', 'Maj2'], dtype=object)

In [134]:
Functional_order = 'Typ', 'Min2', 'Min1', 'Mod', 'Sal', 'Maj1', 'Maj2'
HousePrice['Functional'] = HousePrice['Functional'].astype('category')
HousePrice['Functional'].cat.set_categories(Functional_order, ordered=True, inplace=True)

In [135]:
HousePrice['Fireplaces'].dtype

dtype('int64')

In [137]:
HousePrice['FireplaceQu'].unique()

array(['Gd', nan, 'Ex', 'TA', 'Fa', 'Po'], dtype=object)

In [139]:
FireplaceQu_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['FireplaceQu'] = HousePrice['FireplaceQu'].astype('category')
HousePrice['FireplaceQu'].cat.set_categories(FireplaceQu_order, ordered=True, inplace=True)

In [141]:
HousePrice['GarageType'].unique()

array(['Detchd', 'Attchd', 'BuiltIn', 'Basment', nan, '2Types', 'CarPort'], dtype=object)

In [143]:
GarageType_order = 'Detchd', 'Attchd', 'BuiltIn', 'Basment', '2Types', 'CarPort'
HousePrice['GarageType'] = HousePrice['GarageType'].astype('category')
HousePrice['GarageType'].cat.set_categories(GarageType_order, ordered=True, inplace=True)

In [146]:
HousePrice['GarageType'].unique()

['Detchd', 'Attchd', 'BuiltIn', 'Basment', NaN, '2Types', 'CarPort']
Categories (6, object): ['Detchd' < 'Attchd' < 'BuiltIn' < 'Basment' < '2Types' < 'CarPort']

In [147]:
HousePrice['GarageYrBlt'].dtype

dtype('float64')

In [149]:
HousePrice['GarageFinish'].unique()

array(['Unf', 'Fin', 'RFn', nan], dtype=object)

In [150]:
GarageFinish_order = 'Unf', 'Fin', 'RFn'
HousePrice['GarageFinish'] = HousePrice['GarageFinish'].astype('category')
HousePrice['GarageFinish'].cat.set_categories(GarageFinish_order, ordered=True, inplace=True)

In [151]:
HousePrice['GarageCars'].dtype

dtype('float64')

In [152]:
HousePrice['GarageArea'].dtype

dtype('float64')

In [154]:
HousePrice['GarageQual'].unique()

array(['TA', nan, 'Fa', 'Gd', 'Po', 'Ex'], dtype=object)

In [155]:
GarageQual_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['GarageQual'] = HousePrice['GarageQual'].astype('category')
HousePrice['GarageQual'].cat.set_categories(GarageQual_order, ordered=True, inplace=True)

In [156]:
HousePrice['GarageCond'].unique()

array(['TA', 'Po', nan, 'Fa', 'Gd', 'Ex'], dtype=object)

In [157]:
GarageCond_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['GarageCond'] = HousePrice['GarageCond'].astype('category')
HousePrice['GarageCond'].cat.set_categories(GarageCond_order, ordered=True, inplace=True)

In [158]:
HousePrice['PavedDrive'].unique()

array(['Y', 'N', 'P'], dtype=object)

In [159]:
PavedDrive_order = 'Y', 'N', 'P'
HousePrice['PavedDrive'] = HousePrice['PavedDrive'].astype('category')
HousePrice['PavedDrive'].cat.set_categories(PavedDrive_order, ordered=True, inplace=True)

In [160]:
HousePrice['WoodDeckSF'].dtype

dtype('int64')

In [161]:
HousePrice['OpenPorchSF'].dtype

dtype('int64')

In [162]:
HousePrice['EnclosedPorch'].dtype

dtype('int64')

In [163]:
HousePrice['3SsnPorch'].dtype

dtype('int64')

In [165]:
HousePrice['ScreenPorch'].dtype

dtype('int64')

In [166]:
HousePrice['PoolArea'].dtype

dtype('int64')

In [169]:
HousePrice['PoolQC'].unique()

array([nan, 'Ex', 'Gd', 'Fa', 'TA'], dtype=object)

In [170]:
PoolQC_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['PoolQC'] = HousePrice['PoolQC'].astype('category')
HousePrice['PoolQC'].cat.set_categories(PoolQC_order, ordered=True, inplace=True)

In [172]:
HousePrice['Fence'].unique()

array([nan, 'GdWo', 'MnPrv', 'GdPrv', 'MnWw'], dtype=object)

In [173]:
Fence_order = 'TA', 'Po', 'Fa', 'Gd', 'Ex'
HousePrice['Fence'] = HousePrice['Fence'].astype('category')
HousePrice['Fence'].cat.set_categories(Fence_order, ordered=True, inplace=True)

In [175]:
HousePrice['MiscFeature'].unique()

array([nan, 'Shed', 'Othr', 'Gar2', 'TenC'], dtype=object)

In [176]:
MiscFeature_order = 'Shed', 'Othr', 'Gar2', 'TenC'
HousePrice['MiscFeature'] = HousePrice['MiscFeature'].astype('category')
HousePrice['MiscFeature'].cat.set_categories(MiscFeature_order, ordered=True, inplace=True)

In [177]:
HousePrice['MiscVal'].dtype

dtype('int64')

In [178]:
HousePrice['MoSold'].dtype

dtype('int64')

In [180]:
HousePrice['YrSold'].dtype

dtype('int64')

In [182]:
HousePrice['SaleType'].unique()

array(['WD ', 'ConLD', 'New', 'Oth', 'ConLw', 'COD', 'CWD', 'Con', 'ConLI', 'VWD'], dtype=object)

In [183]:
SaleType_order = 'WD ', 'ConLD', 'New', 'Oth', 'ConLw', 'COD', 'CWD', 'Con', 'ConLI', 'VWD'
HousePrice['SaleType'] = HousePrice['SaleType'].astype('category')
HousePrice['SaleType'].cat.set_categories(SaleType_order, ordered=True, inplace=True)

In [185]:
HousePrice['SaleCondition'].unique()

array(['Normal', 'Partial', 'AdjLand', 'Abnorml', 'Alloca', 'Family'], dtype=object)

In [183]:
SaleCondition_order = 'Normal', 'Partial', 'AdjLand', 'Abnorml', 'Alloca', 'Family'
HousePrice['SaleCondition'] = HousePrice['SaleCondition'].astype('category')
HousePrice['SaleCondition'].cat.set_categories(SaleCondition_order, ordered=True, inplace=True)